name: NickysFixer
version: ${project.version}
main: me.nickyadmin.nickysfixer.Main
authors: [ NickyAdmin ]
description: fixes exploits and adds useful features and also adds some commands :p

commands:
  nickysfixer:
    aliases: [nf, nickysfixes, n]